name: C/C++ CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
      working-directory: ./pft_2019
    - name: run_test
      run: ./test
      working-directory: ./pft_2019
    - name: results.txt
      run: cat results.txt
      working-directory: ./pft_2019
